# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

p 'Start Seed'

Project.create(name: 'My awesome portfolio', short_desc: 'This is a web site developped with Rails', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget pulvinar nisi, sit amet volutpat nibh. Praesent ut risus in velit luctus maximus eget et dui. Sed eget sem magna. Nam eu est eu diam congue mattis. Sed nulla urna, tristique vitae leo vel, lobortis lobortis urna. Sed in diam at arcu luctus vulputate. Maecenas rhoncus rhoncus erat eget pellentesque. Donec eu elit diam. Sed volutpat scelerisque velit, eu rutrum nulla blandit non. Curabitur nec aliquet nunc. Nullam egestas bibendum dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc sit amet mauris a augue porttitor blandit. Nullam sit amet orci dolor. Mauris id aliquet elit, vel aliquet erat. Cras euismod efficitur suscipit.', link: 'localhost:3000')
Project.create(name: 'My awesome portfolio', short_desc: 'This is a web site developped with Rails', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget pulvinar nisi, sit amet volutpat nibh. Praesent ut risus in velit luctus maximus eget et dui. Sed eget sem magna. Nam eu est eu diam congue mattis. Sed nulla urna, tristique vitae leo vel, lobortis lobortis urna. Sed in diam at arcu luctus vulputate. Maecenas rhoncus rhoncus erat eget pellentesque. Donec eu elit diam. Sed volutpat scelerisque velit, eu rutrum nulla blandit non. Curabitur nec aliquet nunc. Nullam egestas bibendum dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc sit amet mauris a augue porttitor blandit. Nullam sit amet orci dolor. Mauris id aliquet elit, vel aliquet erat. Cras euismod efficitur suscipit.', link: 'localhost:3000')
Project.create(name: 'My awesome portfolio', short_desc: 'This is a web site developped with Rails', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget pulvinar nisi, sit amet volutpat nibh. Praesent ut risus in velit luctus maximus eget et dui. Sed eget sem magna. Nam eu est eu diam congue mattis. Sed nulla urna, tristique vitae leo vel, lobortis lobortis urna. Sed in diam at arcu luctus vulputate. Maecenas rhoncus rhoncus erat eget pellentesque. Donec eu elit diam. Sed volutpat scelerisque velit, eu rutrum nulla blandit non. Curabitur nec aliquet nunc. Nullam egestas bibendum dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc sit amet mauris a augue porttitor blandit. Nullam sit amet orci dolor. Mauris id aliquet elit, vel aliquet erat. Cras euismod efficitur suscipit.', link: 'localhost:3000')
Project.create(name: 'My awesome portfolio', short_desc: 'This is a web site developped with Rails', content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse eget pulvinar nisi, sit amet volutpat nibh. Praesent ut risus in velit luctus maximus eget et dui. Sed eget sem magna. Nam eu est eu diam congue mattis. Sed nulla urna, tristique vitae leo vel, lobortis lobortis urna. Sed in diam at arcu luctus vulputate. Maecenas rhoncus rhoncus erat eget pellentesque. Donec eu elit diam. Sed volutpat scelerisque velit, eu rutrum nulla blandit non. Curabitur nec aliquet nunc. Nullam egestas bibendum dapibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc sit amet mauris a augue porttitor blandit. Nullam sit amet orci dolor. Mauris id aliquet elit, vel aliquet erat. Cras euismod efficitur suscipit.', link: 'localhost:3000')

p 'Seed finished'
